* How is the private key of a certificate authority protected in real world? [[security practices]]
* How do asynchronous exceptions in Haskell work? [[haskell]] [[asynchronous programming]]
[[https://dl.acm.org/doi/10.1145/378795.378858][Asynchronous exceptions in Haskell | Proceedings of the ACM SIGPLAN 2001 conference on Programming language design and implementation]]
* Can the operating system stop one program from running without waiting for the preemptive context switch, i.e. must the operating system wait for the time slice of this program to run out? [[further investigation needed]] [[system programming]]
* How can one thread (may be green threads) of a program stop other threads from running? Must we resort to operating system interfaces or use some like ~while (shouldContinue) { doWork(); }~? Does the thread to be killed have a change to clean up?
The operating system actually does not provide syscalls to kill threads. [[https://unix.stackexchange.com/questions/1066/how-can-i-kill-a-particular-thread-of-a-process][shell - How can I kill a particular thread of a process? - Unix & Linux Stack Exchange]]
It is safer to use ~while (shouldContinue) { doWork(); }~[[https://docs.oracle.com/javase/1.5.0/docs/guide/misc/threadPrimitiveDeprecation.html][Java Thread Primitive Deprecation]]