* Why is systemd creating so many bpf programs and bpf maps?
:PROPERTIES:
:heading: true
:END:
A strange two many open files error.
** ~make nixos-switch~
#+BEGIN_QUOTE
make -C ~/Workspace/infra/ nixos-switch
make: Verzeichnis „/home/e/Workspace/infra“ wird betreten
sudo nixos-rebuild switch --flake ".#ssg" --impure --show-trace --keep-going --keep-failed
building the system configuration...
warning: Git tree '/home/e/Workspace/infra' is dirty
trace:

The dream-lock.json for input 'helix-term' doesn't exist or is outdated.
...Falling back to on-the-fly evaluation (possibly slow).
To speed up future evalutations run once:
  nix run .#resolve

trace: warning: aqemu will not be installed as it is marked as broken
trace: warning: pdf2djvu will not be installed as it is marked as broken
trace: warning: haskellPackages.patat will not be installed as it is marked as broken
trace: warning: impressive will not be installed as it is marked as broken
note: keeping build directory '/tmp/nix-build-perl-5.34.0-env.drv-7'
error (ignored): error: opening directory '/nix/store/nq6wcjj673iilp1rwn4iy1sy48nfxbb4-perl-5.34.0-env.drv.chroot/dev': Too many open files
note: keeping build directory '/tmp/nix-build-perl-5.34.0-env.drv-6'
error (ignored): error: opening directory '/nix/store/7d24jic18cz3qaacs5f96gsg3hb60pbr-perl-5.34.0-env.drv.chroot/nix/store/35yz5k6pbhivzmq2vzxjpcr2rks2qiqb-perl-5.34.0-env/lib/perl5/site_perl/5.34.0': Too many open files
note: keeping build directory '/tmp/nix-build-perl-5.34.0-env.drv-8'
note: keeping build directory '/tmp/nix-build-console-env.drv-1'
error: opening directory '/nix/store/1mcmhy8c1kj6n40qyxkv9iv7cmsns7r1-vscode-languageserver-protocol-3.17.0-next.15.tgz': Too many open files
make: *** [Makefile:76: nixos-switch] Fehler 1
make: Verzeichnis „/home/e/Workspace/infra“ wird verlassen 
#+END_QUOTE
** sudo find /proc -maxdepth 1 -type d -name '[0-9]*' \
     -exec bash -c "ls {}/fd/ | wc -l | tr '\n' ' '" \; \
     -printf "fds (PID = %P), command: " \
     -exec bash -c "tr '\0' ' ' < {}/cmdline" \; \
     -exec echo \; | sort -rn | head
#+BEGIN_SRC shell
find: ‘/proc/377947’: No such file or directory
find: ‘/proc/377963’: No such file or directory
find: ‘/proc/377965’: No such file or directory
find: ‘/proc/377966’: No such file or directory
find: ‘/proc/377978’: No such file or directory
757 fds (PID = 1), command: systemd
222 fds (PID = 356200), command: /nix/store/06ygapaf1rwsjvy699r79cwd5gvmg23g-promtail-2.4.2/bin/promtail -config.file=/nix/store/lj3n2bj7i5wvfhlhsj49gmnm1a3f8smf-promtail-config.json -config.expand-env=true
168 fds (PID = 8942), command: /nix/store/sszw4qarha70yvvyrh99k3zmpcsjnmq9-sway-unwrapped-f707f583e17cb5e8323ceb4bfd951ad0465b7d10/bin/sway --verbose --debug
125 fds (PID = 7442), command: /nix/store/87qrmqhsxymz2xrpwbl8h65zgz9q5vq4-moby-20.10.12/libexec/docker/docker-proxy -proto tcp -host-ip :: -host-port 9091 -container-ip 172.18.0.3 -container-port 9091
91 fds (PID = 3838), command: /nix/store/73mgmfvn226llhkxzxj6zjpn3h9qhsah-postfix-3.6.4/libexec/postfix/master -w
88 fds (PID = 1360), command: /nix/store/y4qpl81a6fdjrxwbx9h4xxid64gcn2fi-systemd-249.7/lib/systemd/systemd-journald
75 fds (PID = 2720), command: /nix/store/ams9xm7awckxj1a9w690fq4632xx50ga-prometheus-2.30.3/bin/prometheus --enable-feature=expand-external-labels --enable-feature=agent --storage.tsdb.path=/var/lib/prometheus2/data/ --config.file=/nix/store/0mbmzz1p091m6j4hldqfsld44538ws5y-prometheus.yml-checkconfig-checked --web.listen-address=0.0.0.0:9001 --alertmanager.notification-queue-capacity=10000 --alertmanager.timeout=10s
60 fds (PID = 2784), command: /nix/store/1r9mrh63fc2pgv4h07jhzmxnizididr0-zerotierone-1.8.4/bin/zerotier-one -p9993
52 fds (PID = 2743), command: /nix/store/0saiagm4h9i2bxpjs7fz0p1laa7zczrn-samba-4.15.5/sbin/smbd --foreground --no-process-group
50 fds (PID = 9324), command: /nix/store/f8fcyxn8spqy85dng7c2v0ds9fck1k3l-pipewire-0.3.45/bin/pipewire 
#+END_SRC
** ~sudo bpftool prog show~
#+BEGIN_QUOTE
25: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 24
26: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 23
27: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 26
28: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 25
29: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 28
30: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 27
31: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 30
32: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 29
33: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 32
34: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
        xlated 312B  jited 192B  memlock 4096B  map_ids 31
37: cgroup_skb  tag 7dc8126e8768ea37  gpl
        loaded_at 2022-03-09T22:02:33+0800  uid 0
#+END_QUOTE
** #+BEGIN_SRC shell
sudo bpftool cgroup tree
CgroupPath
ID       AttachType      AttachFlags     Name
/sys/fs/cgroup
8509     ingress         multi
8508     egress          multi
/sys/fs/cgroup/sys-fs-fuse-connections.mount
    8366     ingress         multi
    8365     egress          multi
/sys/fs/cgroup/sys-kernel-config.mount
    8368     ingress         multi
    8367     egress          multi
/sys/fs/cgroup/sys-kernel-debug.mount
    8311     ingress         multi
    8310     egress          multi
/sys/fs/cgroup/dev-mqueue.mount
    8462     ingress         multi
    8461     egress          multi
/sys/fs/cgroup/user.slice
    8360     ingress         multi
    8359     egress          multi
/sys/fs/cgroup/user.slice/user-992.slice
    8399     ingress         multi
    8398     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice
    8326     ingress         multi
    8325     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/session-10.scope
    8442     ingress         multi
    8441     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service
    8286     ingress         multi
    8285     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/session-11.scope
    8333     ingress         multi
    8332     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/session-15.scope
    9071     ingress         multi
    9070     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/session-4.scope
    8288     ingress         multi
    8287     egress          multi
/sys/fs/cgroup/user.slice/user-1000.slice/session-16.scope
    9107     ingress         multi
    9106     egress          multi
#+END_SRC
** [[https://github.com/systemd/systemd/search?q=cgroup_skb&type=code][Search · cgroup_skb]]
**
*