* How to dive deep into some specific topic? It is normally easier to follow people interested in that topic than explore this topic directly by yourself. For instance, if you are interested in classical music, find out what other classical music zealots hoard istead of search for great works yourself.
* Immutable infrastructure with incremental building? An example is container image. Container image itself is immutable, but we can lay one layer on top of another, thus we don't need to build all the this from srcatch. Another example is nixos virtual machine. There are two nix stores in the virtual machine. One is the read only nix store from the host, which is mounted read only by 9pfs/nfs. Another is the nix store of the virtual machine itself. This way we can share most packages between virtual machine and the host. What can ostree do in this problem?
* Some specific example of hardware-software co-design using riscv?
* [[https://maggieappleton.com/evergreens][Growing the Evergreens]]
* [[https://www.dougengelbart.org/content/view/138/][Augmenting Human Intellect: A Conceptual Framework - 1962 (AUGMENT,3906,) - Doug Engelbart Institute]]
* What can I learn from [[https://writings.stephenwolfram.com/2019/02/seeking-the-productive-life-some-details-of-my-personal-infrastructure/][Seeking the Productive Life: Some Details of My Personal Infrastructure—Stephen Wolfram Writings]]? One thing I envy so much is that Wolfram have a personal data orchestration platform to bring all his personal data together. He can search through all his notes, emails. What kind of storage format should I use if I was to build such platform? What kind of user interface should I use? How to schedule all these jobs? It seems Wolfram just use mathematica notebook. This is a proprietary platform which is able to running self-made programs. Most notebooks does not support this level of programbility. I can use jupyter. But each jupyter book seems to be a data silo. It is an isolated notebook having no exterior connection.
* How to establish an ssh connection over quic? [[https://www.ietf.org/archive/id/draft-bider-ssh-quic-09.html][QUIC-based UDP Transport for Secure Shell (SSH)]].
This draft uses the same port for quic and ssh.
A distinction is allowed by that SSH/QUIC only requires the sending of 
QUIC Short Header Packets. Therefore, all UDP datagrams where the first 
byte has its high bit set MUST be handled as part of an SSH/QUIC key 
exchange.
This is not ideal. As this ssh-specific logic need to be processed by the quic server. Can we embed this ssh-specific logic in quic using a generic method? That is to say, we want to wrap the ssh connection completely in quic (thus requires no changes to the quic server) and the mechanism should not be limited to ssh connection. Does quic support that?
* An webrtc based vpn for easy hole punching? The problem is that we can not connect to a vpn peer behind a NAT. Webrtc has so many features (STUN/TURN/ICE) to establish connection between two peers. Why don't we just use webrtc for connection setup? [[https://github.com/pojntfx/weron][pojntfx/weron: Overlay networks based on WebRTC.]]
* How to setup a [[https://github.com/matrix-org/pinecone][matrix-org/pinecone: Peer-to-peer overlay routing for the Matrix ecosystem]] overlay network? Is it designed to do such thing?
* Proof of owner interaction? I have a ssh key stored in the ssh agent. I want some program to be able to use this key, as long as I, the owner, confirmed that this program can use the ssh key. This is like administer confirmation dialog in Windows, or gksudo in Linux. But what I want is a generic programable interface. How does Windows prompt administer confirmation dialog? What does it do? How do I make this interface generic so that other applications can use. Can I use fido for that? It is some kind of chanlledge-response thing.
* Recommended way to expose local file system to an ssh server. We can easily mount remote ssh server storage with sshfs. But what about server access local client files? One use case is that I don't want secrets to be stored in untrusted server. I want it to be accessed on demand. Plan 9 supports this out of the box. What about Linux? We can of course do ssh port forwarding, but this is a dirty hack. [[https://superuser.com/questions/616182/how-to-mount-local-directory-to-remote-like-sshfs][linux - how to mount local directory to remote like sshfs? - Super User]] [[https://github.com/lima-vm/sshocker][lima-vm/sshocker: ssh + reverse sshfs + port forwarder, in Docker-like CLI (predecessor of Lima)]]