* Let \( v \) be a vector, denote right shift \( v \) by n by \( v^{^\rightarrow  n} \). What is the relationship between the polynomial commitment of \( v \) and \( v^{^\rightarrow  n} \)? Give relationship for both schemes in ((6342705c-75ea-449a-8f7b-8076492c1724)). What about left shift?
* Let \( \sigma: [n] \to [n] \) be a permutation of the set \( [n] := {i \in \Z: 0\le i < n} \). Assume \( \omega \) is a generator of a order \(n\) multiplicative subgroup of a finite field. Let \(f\) (respective \(g\)) be the polynomial satisfies \( f(\omega^i) = x_i \) (respectively \( g(\omega^i) = x_{\omega(i)} \)) for some \( x_i \) in the finite field. What's the relationship between \(f\) and \(g\)?
* In order to check the Hadamard product of two vectors \(a\) and \(b\) are 0. The paper [[https://eprint.iacr.org/2021/710][VOProof: Efficient zkSNARKs from Vector Oracle Compilers]] construct a polynomial \( h(x) = f(\omega X^{-1} * g(x)) \) where \(f, g\) are the polynomials coresponds to \(a, b\). It then shows the constant term of \(h\) is zero. In order to do so, it requires the prover to show that \( h(x) = \bar{h}(x) - \bar{h}(\gamma x) \).