* [[https://arxiv.org/abs/2103.04330][[2103.04330] An Overview of Cryptographic Accumulators]] [[cryptographic accumulators]]
* Why doesn't Zerocoin use accumulator to prove the inclusion/non-inclusion of serial numbers? [[cryptographic accumulators]] [[Zerocoin]]
[[https://ieeexplore.ieee.org/abstract/document/6547123][Zerocoin: Anonymous Distributed E-Cash from Bitcoin | IEEE Conference Publication | IEEE Xplore]]
In order to use accumulator to prove the membership/non-membership of a serial number in the unspent serial number list, we need to convert the serial number to a prime number in the range \( [A, B) \), this may be a problem. Another problem is that, we use unique serial numbers to prevent double spending. Will there be a double spent problem if we use accumulator?
* Why don't we just store a list of commitments instead of the accumulator now that the commitments are public in Zerocoin? Is it for space efficiency? [[cryptographic accumulators]] [[Zerocoin]]
* How do we convert generic identifiers to prime numbers in order to use accumulators in [[https://link.springer.com/chapter/10.1007/3-540-45708-9_5][Dynamic Accumulators and Application to Efficient Revocation of Anonymous Credentials | SpringerLink]]? [[cryptographic accumulators]]
Hash to prime numbers? Give a concrete example. [[https://github.com/cambrian/accumulator/blob/master/src/hash/mod.rs#L45-L64][accumulator/mod.rs at master · cambrian/accumulator · GitHub]]
* Can we construct a zero knowledge elementary database scheme from a zero knowledge set scheme? [[zero knowledge proofs]]
We can convert any proposition of the form \( (k, v) \in T \) (which represents the key-value pair \( (k, v) \) is in the database) to proposition of the form \( s \in S \) (which represents the element \( s \) is in the set).
* How does using class group instead of RSA group eliminate the need for a trusted setup? [[cryptography]] [[class groups]]
[[https://cambrian.github.io/accumulator/docs/][accumulator - Rust]]
#+BEGIN_QUOTE
The RSA group is fast but relies on the security of the RSA-2048 modulus and needs trusted setup if using a different modulus. The class group is slower but eliminates the need for a trusted setup. For more on class groups, please visit this thorough explainer by contributor Michael Straka.
#+END_QUOTE