* How does rollback protection in Android and Chrome OS works? [[security]]
[[https://source.android.com/docs/security/features/verifiedboot/verified-boot#rollback-protection][Verifying Boot  |  Android Open Source Project]]
[[https://android.googlesource.com/platform/external/avb/+/master/README.md#Rollback-Protection][Android Verified Boot 2.0]]
* Any kind of side channel attacks for amd sev? [[AMD Secure Encrypted Virtualization]] [[side-channel attacks]]
[[https://www.amd.com/en/processors/amd-secure-encrypted-virtualization][AMD Secure Encrypted Virtualization | AMD]]
#+BEGIN_QUOTE
Additionally, SEV-SNP optionally supports the ability to restrict how interrupts and exceptions can be injected into a VM. It can also support Branch Target Buffer (BTB) protection against certain types of side channel attacks. Both protections are discussed later in this white paper.
#+END_QUOTE
* Any checklist of cryptographic libraries authors to avoid side-channel attacks? [[side-channel attacks]] [[development practices]]
* How is the owner of a physical page in AMD SEV reverse map table tracked? [[operating system]]
The normal page table is created per process. When the operating system is doing context switch, it also changes [[https://wiki.osdev.org/CPU_Registers_x86#CR3][the register cr3 in x86]] (level 0 of the page table). Thus the owner of a page table can be easily tracked by the operating system. On the other hand, the reverse map table maps the physical memory address to the owner information of that page.
#+BEGIN_QUOTE
e RMP is a single data structure shared across the
system that contains one entry for every 4k page of DRAM that may be used by VMs. The goal of the
RMP is simple: it tracks the owner for each page of memory. Pages of memory can be owned by the
hypervisor, owned by a specific VM, or owned by the AMD-SP. Access to memory is controlled so only
the owner of that page can write it. The RMP is used in conjunction with standard x86 page tables to enforce page 
#+END_QUOTE
 
It seems there exists only one AMD SEV reverse map table. Where can the owner information stored in the reverse map table?