* Elaborate on archiving privacy with re-randomization. Give a concrete example. [[neptune cash]]
[[https://neptune.cash/whitepaper/][Neptune whitepaper]]
#+BEGIN_QUOTE
The re-randomizability of the commitment scheme is an essential 
quality for privacy as it achieves de-linking the output UTXOs of 
confirmed transactions from the input UTXOs of new transactions. 
Specifically, to the outside observer (who has no access to the miner's 
randomness) the output and input UTXOs are unlinkable even though they 
decommit to the same or matching information.
#+END_QUOTE
* [[https://github.com/opentimestamps/opentimestamps-server/blob/master/doc/merkle-mountain-range.md][opentimestamps-server/merkle-mountain-range.md at master · opentimestamps/opentimestamps-server · GitHub]] [[merkle mountain range]]
A variant of Merkle tree to accumulate new elements.
* What is the use of offset in FRI? [[fast Reed-Solomon interactive oracle proofs of proximity]]
In FRI, we evaluate/interpolate in the coset of \( \{\omega^i\} \) instead \( \{\omega^i\} \) itself. Is it used for obfuscation?
[[https://aszepieniec.github.io/stark-anatomy/stark#fnref:1][Anatomy of a STARK, Part 4: The STARK Polynomial IOP | Anatomy of a STARK]]
#+BEGIN_QUOTE
It is worth ensuring that the trace evaluation domain is disjoint from 
the FRI evaluation domain, for example by using the coset-trick. 
However, if overlapping subgroups are used for both domains, then \( \omega^{1/\rho} = \omicron \) and \( \omega \) generates the larger domain whereas \( \omicron \) generates the smaller one.
#+END_QUOTE