* Ring signature scheme with Schnorr signature. [[Schnorr signatures]] [[ring signatures]]
[[https://www.getmonero.org/library/RingsCheatsheet20210301.pdf][Ring signature cheatcheet]].
* How do the payer and payee know the payment amount in Monero? [[monero]]
[[https://www.getmonero.org/library/RctCheatsheet20210604.pdf][ring confidential transaction cheatsheet]]
#+BEGIN_QUOTE
amount is the way payer and payee secretly share the value: the payer calculates it from the plain value ~a~ by the given definition; the payee can get back and verify the plain value a by just XORing the amount with the same hash function used in its definition (two equal XORs elide themselves). To have an hash computable by both payer and payee, transaction and view keys are used in the same Diffie-Hellman-like way they are in stealth addresses generation.
#+END_QUOTE
The encrypted amount is defined to be \(a \oplus H( \text{"amount"} , H(r V_i , t)) \) where \( r \) seems to be the private transaction key and \( V_i \) the payee's viewkey. Since \( r V_i =  r v_i g = v_i r g = v_i R \) (where \( g \) is the generator of the elliptic group, \( v_i \) is the secret viewkey, and \( R \) is the  )
*
*