* How to construct a ring signature scheme from one-way permutation with trapdoor, symmetric encryption and hash function? [[ring signatures]]
Given a set of public keys \( p_i \) and their respective encryption method \( f_i \) (with the trapdoor inverses \( g_i = f_i^{-1} \) known only who with the private key corresponding to \( p_i \)), we can construct a ring signature scheme as follows. Let \( s \) be the index of the real signer, \( m \) the message to sign, \( E_k \) the symmetric encryption function (where \( k = H(m) \) is the hash digest of the message \( m \))
* How to construct a signature scheme and an encryption scheme from one-way permutation with trapdoor? [[signature schemes]] [[RSA signature scheme]]
TODO: something is wrong here.
Let \( n = p * q \) be a product of two large primes \( p, q \), let \( e < n \) be a random nature number, \( m < n \) be the "message" to encrypt. Then the encrypted message of \( m \) in RSA encryption scheme \( m^\prime \) is \( E(m) = m^e \text{ mod } n \). One can decrypt this message by \( D(m^\prime) = {(m^\prime)}^f \), where \( f \) is a number coprime to \( e \). We can construct a signature scheme from this. Let \( v \) be a message to sign, the signature of this message is \( (H(v), D(H(v)) \).
This can be signature generalized to one-way permutation with trapdoor. Just take the permutation as \( E \), and its inverse as \( D \).
*