* Batch opening multiple polynomials at multiple points of a polynomial commitment scheme. [[polynomial commitments]]
[[https://eprint.iacr.org/2020/1536.pdf][Halo Infinite: Proof-Carrying Data from Additive Polynomial Commitments]]
#+BEGIN_QUOTE
Previously, standard batched evaluation techniques for homomorphic polynomial commitments included: (1) opening distinct commitments at the same point, and (2) opening a single commitment at multiple points. The first is accomplished by opening a random linear combination of the original commitments. The second is accomplished by interpolating a degree-n polynomial t over the n opening points such that the committed polynomial f is equal to t over the domain H of these points, andproving that f − t is divisible by the zero polynomial zH over this domain. The prover computes a
commitment Cq to the quotient polynomial q := f −t
zH and proves that q · ZH = (f − t) by opening Cq
and Cf at a random challenge point. Both of these standard batch evaluation protocols are single-
round. We elegantly compose these two approaches to get a two-round protocol for batch opening
multiple polynomials at multiple points.
#+END_QUOTE