name: Daily Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get daily version
        id: version
        run: |
          set -xeuo pipefail
          git fetch --tags
          currentTag="$(git tag --points-at HEAD)"
          if [[ -z "$currentTag" ]]; then
              version="v$(date -u +"%Y.%m.%d")"
              count="$(git tag -l "$version*" | wc -l)"
              if (( $count > 0 )); then
                  version="$version-$count"
              fi
              git tag "$version"
              git push --tags
              echo "::set-output name=version::$version"
          fi
      - uses: fregante/release-with-changelog@v3
        if: steps.version.outputs.version != ''
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
